function OnPointerClick()
    local helpMnl = GetParent(EntityID)
    local canvas = GetParent(helpMnl)
    local mainBg = GetChildren(canvas, 0)
    local playBtn = GetChildren(canvas, 1)
    local helpBtn = GetChildren(canvas, 2)
    local credBtn = GetChildren(canvas, 3)
    local quitBtn = GetChildren(canvas, 4)
    SetActiveEntity(mainBg, true)
    SetActiveEntity(playBtn, true)
    SetActiveEntity(helpBtn, true)
    SetActiveEntity(credBtn, true)
    SetActiveEntity(quitBtn, true)
    SetActiveEntity(helpMnl, false)

    --GetAudioComponent():play(EntityID, "Menu Click")
end